#!/usr/bin/env python3
"""Regenerate the freestanding float runtime IR using the Ryn compiler.

The source is selfhost/src/float_runtime.ryn and middle/floatlib.ryn. Embedded
IR lets the native backend compile the same exact algorithms into each binary,
without reading compiler sources from disk or depending on a host compiler.
"""
import json
from pathlib import Path
import re
import subprocess
import tempfile
import os

ROOT = Path(__file__).resolve().parents[1]
with tempfile.TemporaryDirectory(prefix="ryn-float-runtime-") as directory:
    subprocess.run([str(ROOT / "target/release/ryn"), "check", "selfhost/src/float_runtime.ryn"],
                   cwd=ROOT, env=dict(os.environ, RYN_DUMP_SEMA=directory), check=True)
    text = (Path(directory) / "ryn.ir").read_text().strip()
# The entry calls precisely the two runtime wrappers. Derive their IDs from the
# terminal main definition, rather than relying on the lowerer's function order.
match = re.search(r"CallStatement Function (\d+) 2 Integer 0 U64 Boolean 0 CallStatement Function (\d+) 2 String 0: Boolean 0 Drop 0 0 0 0$", text)
if match is None:
    raise SystemExit("unexpected runtime entry IR; inspect before regenerating")
output = "// Generated by tools/update-native-float-runtime.py; edit float_runtime.ryn or middle/floatlib.ryn.\n"
output += f"pub fun format_index() -> u64 {{ return {match[1]} }}\n"
output += f"pub fun parse_index() -> u64 {{ return {match[2]} }}\n"
output += "pub fun source_ir() -> String {\n    return String(" + json.dumps(text, ensure_ascii=False) + ")\n}\n"
(ROOT / "selfhost/src/back/float_runtime_ir.ryn").write_text(output)
